name: calc_steps_mobile
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.0
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - image/svg/
    - image/ex/factorize/
    - image/ex/exponent/
    - image/ex/root/
    - image/ms/factorize/
    - image/ms/exponent/
    - image/ms/root/

fonts:
  - family: Lato
    fonts:
    - assets: fonts/Lato-Bold.ttf
    - assets: fonts/Lato-Regular.ttf